baseURL = 'https://hurricaneshark.com/'
languageCode = 'en-us'
title = 'Hurricane Shark'
theme = "smol"
disableLiveReload = true

# Parameters
[params]
    subtitle = "Reverse Engineering, Pen Testing, and Bad Guitar Solos"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/hurricaneshark"
        weight = 1 
